---
- hosts: localhost
  become: true
  vars:
    system_user: robert      
    php_timezone: Europe/Berlin
    php_upload_max_filesize: "768M"
    php_post_max_size: "768M"
    php_max_execution_time: 500
    php_packages:
      - php7.1-common
      - php7.1-cli
      - php7.1-intl
      - php7.1-curl
      - php7.1-fpm
      - php7.1-gd
      - php7.1-mbstring
      - php7.1-mcrypt        
      - php7.1-pdo-sqlite

    nginx_vhosts:
      - listen: "80"
        server_name: "localhost"
        root: "/home/{{ system_user }}/web/www"
        index: "index.php index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "localhost.conf"
        extra_parameters: |
          location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
          }
  roles:
    - geerlingguy.nginx
    - itcraftsmanpl.php7  
  tasks:
    - name: web folder exists
      file: 
        path: "/home/{{ system_user }}/web"
        state: directory
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        mode: "755"
    - name: web folder exists
      file:
        path: "/home/{{ system_user }}/web/www"
        state: directory
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        mode: "755"



